### PR TITLE
Redstone-controlled traffic lights + rotatable signs + blocks with different heights

### PR DESCRIPTION
**Pull request by E-Mans-Application**
Sign can be rotated in 16 directions (instead of 4)

    All road blocks come with 4 different height: 0.25, 0.5, 0.75 (default), 1 (full cube)
    See crafts and how to make slopes in the readme file.

    Change in the way redstone-controlled traffic lights work (no longer switch on every impulse)
        powered on = yellow/red
        powered off = green.

    A few new road signs (English translations not guaranteed)

    Added a config file to disable asphalt generation (untested, hope it works)

    I hope I forgot nothing

Updating should not break your map, but I suggest you save it anyway before trying.

### CODE REVIEW

**Comment by derfl007** [comment]
Thanks a lot, i will consider this in the next update, i have been trying to update it to 1.14 but it proved to be more complicated than i first thought. Anyway, I won't merge the PR for now, as I'm more focused on the 1.14 update. I can't say if I will add all those changes to the 1.12 version as well.

**Comment by derfl007** [comment]
Dude thank you, I just realized how much you've been contributing and I totally ignored you. I am so sorry lol. 
Do you have a jar file handy? If yes, feel free to send it to me, and I'll upload it on the mod pages on curseforge and planetminecraft (with lots of credit to you of course!!)
If not I can also build it myself, no problem!

Edit: I actually just realized that I don't really have my IDE setup correctly at the moment, so if you have the jar that would be great lol

**Comment by E-Mans-Application** [comment]
Hello, 

No problem!
I have indeed uploaded a jar file in the release section, in my fork.

There are still a few points to improve, but it works.

**Comment by derfl007** [comment]
Ah great thank you, I'll update it tomorrow then!

**Comment by derfl007** [comment]
Hey, I updated the file, and thanked you in the changelogs, is there any other way I can credit you? A youtube channel, a curseforge account, whatever?

**Pull request merged**
